# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81cf8a3871984d8f902b8c7a0ec4ed4b50f7c10c57f5e82cd4378c597a71080900ba47901966db9162de026babd755ad7aa1744aabe7270292795040d72c31d6

test:
  secret_key_base: 170c280bb004f746f0d0def0a7b50c845e884d7185cf502ec803c95fedc1e36a94556e109decd0b11cd371736ca80bb9b3d83d1116ad6c3ed139bd1fc413f0cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
